name: Formal Release

on:
  pull_request:
    types: [closed]

jobs:
  call-formal-release:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      github.event.pull_request.user.login == 'fedi-libs-release-bot[bot]'
    uses: fedi-libs/release-manager/.github/workflows/reusable-formal-release.yml@main
    with:
      head_ref: ${{ github.event.pull_request.head.ref }}
      pr_body: ${{ github.event.pull_request.body }}
    secrets:
      app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
      private_key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
  deploy-docs:
     uses: ./.github/workflows/docs.yml